<?xml version="1.0" encoding="utf-8"?><Database Name="AdventureWorks" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=FSHARPSRV08;Initial Catalog=AdventureWorks;Integrated Security=True" Provider="System.Data.SqlClient" />
  <Table Name="HumanResources.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentID" Type="System.Int16" DbType="SmallInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Department_EmployeeDepartmentHistory" Member="EmployeeDepartmentHistories" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="EmployeeDepartmentHistory" />
    </Type>
  </Table>
  <Table Name="HumanResources.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NationalIDNumber" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ContactID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoginID" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ManagerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaritalStatus" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="HireDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SalariedFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VacationHours" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="SickLeaveHours" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="CurrentFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Employee" Member="Employees" ThisKey="EmployeeID" OtherKey="ManagerID" Type="Employee" />
      <Association Name="Employee_EmployeeAddress" Member="EmployeeAddresses" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EmployeeAddress" />
      <Association Name="Employee_EmployeeDepartmentHistory" Member="EmployeeDepartmentHistories" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EmployeeDepartmentHistory" />
      <Association Name="Employee_EmployeePayHistory" Member="EmployeePayHistories" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="EmployeePayHistory" />
      <Association Name="Employee_JobCandidate" Member="JobCandidates" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="JobCandidate" />
      <Association Name="Employee_Employee" Member="Employee1" ThisKey="ManagerID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="HumanResources.EmployeeAddress" Member="EmployeeAddresses">
    <Type Name="EmployeeAddress">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AddressID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Employee_EmployeeAddress" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="HumanResources.EmployeeDepartmentHistory" Member="EmployeeDepartmentHistories">
    <Type Name="EmployeeDepartmentHistory">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int16" DbType="SmallInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ShiftID" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Department_EmployeeDepartmentHistory" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
      <Association Name="Employee_EmployeeDepartmentHistory" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="Shift_EmployeeDepartmentHistory" Member="Shift" ThisKey="ShiftID" OtherKey="ShiftID" Type="Shift" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="HumanResources.EmployeePayHistory" Member="EmployeePayHistories">
    <Type Name="EmployeePayHistory">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RateChangeDate" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rate" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="PayFrequency" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Employee_EmployeePayHistory" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="HumanResources.JobCandidate" Member="JobCandidates">
    <Type Name="JobCandidate">
      <Column Name="JobCandidateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Resume" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Employee_JobCandidate" Member="Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="HumanResources.Shift" Member="Shifts">
    <Type Name="Shift">
      <Column Name="ShiftID" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Shift_EmployeeDepartmentHistory" Member="EmployeeDepartmentHistories" ThisKey="ShiftID" OtherKey="ShiftID" Type="EmployeeDepartmentHistory" />
    </Type>
  </Table>
  <Table Name="HumanResources.vEmployee" Member="vEmployees">
    <Type Name="vEmployee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Suffix" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" />
      <Column Name="EmailAddress" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailPromotion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine1" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="AddressLine2" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="StateProvinceName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CountryRegionName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalContactInfo" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Function Name="dbo.uspGetBillOfMaterials" Method="uspGetBillOfMaterials">
    <Parameter Name="StartProductID" Parameter="startProductID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CheckDate" Parameter="checkDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="uspGetBillOfMaterialsResult">
      <Column Name="ProductAssemblyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComponentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComponentDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TotalQuantity" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="StandardCost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ListPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="BOMLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RecursionLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="HumanResources.uspUpdateEmployeePersonalInfo" Method="uspUpdateEmployeePersonalInfo">
    <Parameter Name="EmployeeID" Parameter="employeeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="NationalIDNumber" Parameter="nationalIDNumber" Type="System.String" DbType="NVarChar(15)" />
    <Parameter Name="BirthDate" Parameter="birthDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MaritalStatus" Parameter="maritalStatus" Type="System.Char" DbType="NChar(1)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Char" DbType="NChar(1)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspGetEmployeeManagers" Method="uspGetEmployeeManagers">
    <Parameter Name="EmployeeID" Parameter="employeeID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspGetEmployeeManagersResult">
      <Column Name="RecursionLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ManagerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ManagerFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ManagerLastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetManagerEmployees" Method="uspGetManagerEmployees">
    <Parameter Name="ManagerID" Parameter="managerID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspGetManagerEmployeesResult">
      <Column Name="RecursionLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ManagerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ManagerFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ManagerLastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspGetWhereUsedProductID" Method="uspGetWhereUsedProductID">
    <Parameter Name="StartProductID" Parameter="startProductID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CheckDate" Parameter="checkDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="uspGetWhereUsedProductIDResult">
      <Column Name="ProductAssemblyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComponentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ComponentDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TotalQuantity" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="StandardCost" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ListPrice" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="BOMLevel" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="RecursionLevel" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.uspLogError" Method="uspLogError">
    <Parameter Name="ErrorLogID" Parameter="errorLogID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.uspPrintError" Method="uspPrintError">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="HumanResources.uspUpdateEmployeeHireInfo" Method="uspUpdateEmployeeHireInfo">
    <Parameter Name="EmployeeID" Parameter="employeeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="HireDate" Parameter="hireDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="RateChangeDate" Parameter="rateChangeDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Rate" Parameter="rate" Type="System.Decimal" DbType="Money" />
    <Parameter Name="PayFrequency" Parameter="payFrequency" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="CurrentFlag" Parameter="currentFlag" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="HumanResources.uspUpdateEmployeeLogin" Method="uspUpdateEmployeeLogin">
    <Parameter Name="EmployeeID" Parameter="employeeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ManagerID" Parameter="managerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="LoginID" Parameter="loginID" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="HireDate" Parameter="hireDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="CurrentFlag" Parameter="currentFlag" Type="System.Boolean" DbType="Bit" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ufnGetAccountingEndDate" Method="ufnGetAccountingEndDate" IsComposable="true">
    <Return Type="System.DateTime" />
  </Function>
  <Function Name="dbo.ufnLeadingZeros" Method="ufnLeadingZeros" IsComposable="true">
    <Parameter Name="Value" Parameter="value" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.ufnGetAccountingStartDate" Method="ufnGetAccountingStartDate" IsComposable="true">
    <Return Type="System.DateTime" />
  </Function>
  <Function Name="dbo.ufnGetContactInformation" Method="ufnGetContactInformation" IsComposable="true">
    <Parameter Name="ContactID" Parameter="contactID" Type="System.Int32" DbType="Int" />
    <ElementType Name="ufnGetContactInformationResult">
      <Column Name="ContactID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="JobTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ContactType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ufnGetDocumentStatusText" Method="ufnGetDocumentStatusText" IsComposable="true">
    <Parameter Name="Status" Parameter="status" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.ufnGetProductDealerPrice" Method="ufnGetProductDealerPrice" IsComposable="true">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="OrderDate" Parameter="orderDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Decimal" />
  </Function>
  <Function Name="dbo.ufnGetProductListPrice" Method="ufnGetProductListPrice" IsComposable="true">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="OrderDate" Parameter="orderDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Decimal" />
  </Function>
  <Function Name="dbo.ufnGetProductStandardCost" Method="ufnGetProductStandardCost" IsComposable="true">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Parameter Name="OrderDate" Parameter="orderDate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Decimal" />
  </Function>
  <Function Name="dbo.ufnGetPurchaseOrderStatusText" Method="ufnGetPurchaseOrderStatusText" IsComposable="true">
    <Parameter Name="Status" Parameter="status" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.ufnGetSalesOrderStatusText" Method="ufnGetSalesOrderStatusText" IsComposable="true">
    <Parameter Name="Status" Parameter="status" Type="System.Byte" DbType="TinyInt" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.ufnGetStock" Method="ufnGetStock" IsComposable="true">
    <Parameter Name="ProductID" Parameter="productID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>